import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How widespread do companies think corruption is in their country?",
  "subtitle": "In 2025, 63% of EU-based companies considered corruption to be ‘very’ or ‘fairly widespread’ in their country. The share ranged from 18% in Denmark to 97% in Greece.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nBelgium,BE,0.54,false,54% of companies,,,,,,,,\nBulgaria,BG,0.89,false,89% of companies,,,,,,,,\nCzechia,CZ,0.62,false,62% of companies,,,,,,,,\nDenmark,DK,0.18,false,18% of companies,,,,,,,,\nGermany,DE,0.47,false,47% of companies,,,,,,,,\nEstonia,EE,0.32,false,32% of companies,,,,,,,,\nIreland,IE,0.30,false,30% of companies,,,,,,,,\nGreece,EL,0.97,false,97% of companies,,,,,,,,\nSpain,ES,0.87,false,87% of companies,,,,,,,,\nFrance,FR,0.63,false,63% of companies,,,,,,,,\nCroatia,HR,0.90,false,90% of companies,,,,,,,,\nItaly,IT,0.81,false,81% of companies,,,,,,,,\nCyprus,CY,0.93,false,93% of companies,,,,,,,,\nLatvia,LV,0.66,false,66% of companies,,,,,,,,\nLithuania,LT,0.56,false,56% of companies,,,,,,,,\nLuxembourg,LU,0.40,false,40% of companies,,,,,,,,\nHungary,HU,0.83,false,83% of companies,,,,,,,,\nMalta,MT,0.69,false,69% of companies,,,,,,,,\nNetherlands,NL,0.52,false,52% of companies,,,,,,,,\nAustria,AT,0.55,false,55% of companies,,,,,,,,\nPoland,PL,0.41,false,41% of companies,,,,,,,,\nPortugal,PT,0.75,false,75% of companies,,,,,,,,\nRomania,RO,0.90,false,90% of companies,,,,,,,,\nSlovenia,SI,0.84,false,84% of companies,,,,,,,,\nSlovakia,SK,0.85,false,85% of companies,,,,,,,,\nFinland,FI,0.28,false,28% of companies,,,,,,,,\nSweden,SE,0.45,false,45% of companies,,,,,,,,",
  "parsedData": [
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.54,
      "extraInfo": false,
      "text_content": "54% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.89,
      "extraInfo": false,
      "text_content": "89% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.62,
      "extraInfo": false,
      "text_content": "62% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.18,
      "extraInfo": false,
      "text_content": "18% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.47,
      "extraInfo": false,
      "text_content": "47% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.32,
      "extraInfo": false,
      "text_content": "32% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.3,
      "extraInfo": false,
      "text_content": "30% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.97,
      "extraInfo": false,
      "text_content": "97% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.87,
      "extraInfo": false,
      "text_content": "87% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.63,
      "extraInfo": false,
      "text_content": "63% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.9,
      "extraInfo": false,
      "text_content": "90% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.81,
      "extraInfo": false,
      "text_content": "81% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.93,
      "extraInfo": false,
      "text_content": "93% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.66,
      "extraInfo": false,
      "text_content": "66% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.56,
      "extraInfo": false,
      "text_content": "56% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.4,
      "extraInfo": false,
      "text_content": "40% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.83,
      "extraInfo": false,
      "text_content": "83% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.69,
      "extraInfo": false,
      "text_content": "69% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.52,
      "extraInfo": false,
      "text_content": "52% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.55,
      "extraInfo": false,
      "text_content": "55% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.41,
      "extraInfo": false,
      "text_content": "41% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.75,
      "extraInfo": false,
      "text_content": "75% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.9,
      "extraInfo": false,
      "text_content": "90% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.84,
      "extraInfo": false,
      "text_content": "84% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.85,
      "extraInfo": false,
      "text_content": "85% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.28,
      "extraInfo": false,
      "text_content": "28% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.45,
      "extraInfo": false,
      "text_content": "45% of companies",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurobarometer 557",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "The figures show the share of companies that consider the problem of corruption to be either ‘very widespread’ or ‘fairly widespread’ in their country. The data reflect companies’ perceptions and do not measure the actual incidence of corruption. The survey was conducted between January and February 2025 among 12,923 companies across the EU.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://europa.eu/eurobarometer/surveys/detail/3382",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of companies consider corruption widespread",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How widespread do companies think corruption is in their country?",
    "subtitle": "In 2025, 63% of EU-based companies considered corruption to be ‘very’ or ‘fairly widespread’ in their country. The share ranged from 18% in Denmark to 97% in Greece.",
    "textNoteDescription": "Note",
    "textNote": "The figures show the share of companies that consider the problem of corruption to be either ‘very widespread’ or ‘fairly widespread’ in their country. The data reflect companies’ perceptions and do not measure the actual incidence of corruption. The survey was conducted between January and February 2025 among 12,923 companies across the EU.",
    "textSourceDescription": "Source",
    "textSource": "Eurobarometer 557",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_BE": "54% of companies",
    "extraInfo_BG": "89% of companies",
    "extraInfo_CZ": "62% of companies",
    "extraInfo_DK": "18% of companies",
    "extraInfo_DE": "47% of companies",
    "extraInfo_EE": "32% of companies",
    "extraInfo_IE": "30% of companies",
    "extraInfo_EL": "97% of companies",
    "extraInfo_ES": "87% of companies",
    "extraInfo_FR": "63% of companies",
    "extraInfo_HR": "90% of companies",
    "extraInfo_IT": "81% of companies",
    "extraInfo_CY": "93% of companies",
    "extraInfo_LV": "66% of companies",
    "extraInfo_LT": "56% of companies",
    "extraInfo_LU": "40% of companies",
    "extraInfo_HU": "83% of companies",
    "extraInfo_MT": "69% of companies",
    "extraInfo_NL": "52% of companies",
    "extraInfo_AT": "55% of companies",
    "extraInfo_PL": "41% of companies",
    "extraInfo_PT": "75% of companies",
    "extraInfo_RO": "90% of companies",
    "extraInfo_SI": "84% of companies",
    "extraInfo_SK": "85% of companies",
    "extraInfo_FI": "28% of companies",
    "extraInfo_SE": "45% of companies"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_BE": "54% of companies",
  "extraInfo_BG": "89% of companies",
  "extraInfo_CZ": "62% of companies",
  "extraInfo_DK": "18% of companies",
  "extraInfo_DE": "47% of companies",
  "extraInfo_EE": "32% of companies",
  "extraInfo_IE": "30% of companies",
  "extraInfo_EL": "97% of companies",
  "extraInfo_ES": "87% of companies",
  "extraInfo_FR": "63% of companies",
  "extraInfo_HR": "90% of companies",
  "extraInfo_IT": "81% of companies",
  "extraInfo_CY": "93% of companies",
  "extraInfo_LV": "66% of companies",
  "extraInfo_LT": "56% of companies",
  "extraInfo_LU": "40% of companies",
  "extraInfo_HU": "83% of companies",
  "extraInfo_MT": "69% of companies",
  "extraInfo_NL": "52% of companies",
  "extraInfo_AT": "55% of companies",
  "extraInfo_PL": "41% of companies",
  "extraInfo_PT": "75% of companies",
  "extraInfo_RO": "90% of companies",
  "extraInfo_SI": "84% of companies",
  "extraInfo_SK": "85% of companies",
  "extraInfo_FI": "28% of companies",
  "extraInfo_SE": "45% of companies"
});